import { TableSeed } from '@core/database/seeds'

/**
 * 各表默认初始化数据（来源于参考项目 mysql_node_api 的 sql.sql，
 * 并改写为 design_api 的 code / ref_code 语义）。
 * 仅在数据库中存在该表时同步；同步策略为“只补缺失行，不覆盖、不删除”。
 */
export const TABLE_SEEDS: TableSeed[] = [
  // ---------- sensor_data 字段映射（field1..7） ----------
  {
    table: 'sensor_data_mapper',
    keyColumn: 'id',
    rows: [
      {
        id: 1,
        f_name: 'ID',
        db_name: 'id',
        p_name: 'id',
        api_name: null,
        unit: '',
        type: '1',
        visible: '0',
        chartable: '0',
      },
      {
        id: 2,
        f_name: '设备编号',
        db_name: 'd_no',
        p_name: 'id',
        api_name: 'id',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
      },
      {
        id: 3,
        f_name: '数据时间',
        db_name: 'c_time',
        p_name: 'time',
        api_name: 'time',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
      },
      {
        id: 4,
        f_name: '进水温度',
        db_name: 'field1',
        p_name: 'wen_du1',
        api_name: 'temp_in',
        unit: '°C',
        type: '1',
        visible: '1',
        chartable: '1',
      },
      {
        id: 5,
        f_name: '出水温度',
        db_name: 'field2',
        p_name: 'wen_du2',
        api_name: 'temp_out',
        unit: '°C',
        type: '1',
        visible: '1',
        chartable: '1',
      },
      {
        id: 6,
        f_name: '加热开关',
        db_name: 'field3',
        p_name: 'jia_re',
        api_name: 'heat_Y1',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
      },
      {
        id: 7,
        f_name: '水泵状态',
        db_name: 'field4',
        p_name: 'shui_beng',
        api_name: 'water_Y2',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
      },
      {
        id: 8,
        f_name: '流量总计',
        db_name: 'field5',
        p_name: 'liu_liang1',
        api_name: 'liu_liang1',
        unit: 'L',
        type: '1',
        visible: '1',
        chartable: '0',
      },
      {
        id: 9,
        f_name: '瞬时流量',
        db_name: 'field6',
        p_name: 'liu_liang2',
        api_name: 'flow_rate',
        unit: 'L/min',
        type: '1',
        visible: '1',
        chartable: '1',
      },
      {
        id: 10,
        f_name: '水流压力',
        db_name: 'field7',
        p_name: 'pressure',
        api_name: 'pressure',
        unit: 'kPa',
        type: '1',
        visible: '1',
        chartable: '1',
      },
    ],
  },

  // ---------- behavior_data 字段映射（暂无额外字段，仅基础列） ----------
  {
    table: 'behavior_data_mapper',
    keyColumn: 'id',
    rows: [
      {
        id: 1,
        f_name: 'ID',
        db_name: 'id',
        p_name: 'id',
        unit: '',
        type: '1',
        visible: '0',
        chartable: '0',
      },
      {
        id: 2,
        f_name: '设备编号',
        db_name: 'd_no',
        p_name: 'd_no',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
      },
      {
        id: 3,
        f_name: '数据时间',
        db_name: 'c_time',
        p_name: 'c_time',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
      },
    ],
  },

  // ---------- error_msg 字段映射（field1..3） ----------
  {
    table: 'error_msg_mapper',
    keyColumn: 'id',
    rows: [
      {
        id: 1,
        f_name: 'ID',
        db_name: 'id',
        p_name: 'id',
        unit: '',
        type: '1',
        visible: '0',
        chartable: '0',
      },
      {
        id: 2,
        f_name: '设备编号',
        db_name: 'd_no',
        p_name: 'd_no',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
      },
      {
        id: 3,
        f_name: '故障时间',
        db_name: 'c_time',
        p_name: 'c_time',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
      },
      {
        id: 4,
        f_name: '错误信息',
        db_name: 'field1',
        p_name: 'e_msg',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
      },
      {
        id: 5,
        f_name: '错误代码',
        db_name: 'field2',
        p_name: 'e_no',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
      },
      {
        id: 6,
        f_name: '错误类型',
        db_name: 'field3',
        p_name: 'type',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
      },
    ],
  },

  // ---------- control_log 字段映射（field1..5，含值映射词表 mapping） ----------
  {
    table: 'control_log_mapper',
    keyColumn: 'id',
    rows: [
      {
        id: 1,
        f_name: 'ID',
        db_name: 'id',
        p_name: 'id',
        unit: '',
        type: '1',
        visible: '0',
        chartable: '0',
        mapping: null,
      },
      {
        id: 2,
        f_name: '设备编号',
        db_name: 'd_no',
        p_name: 'id',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
        mapping: null,
      },
      {
        id: 3,
        f_name: '操作时间',
        db_name: 'c_time',
        p_name: 'time',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
        mapping: null,
      },
      {
        id: 4,
        f_name: '控制来源',
        db_name: 'field1',
        p_name: 'source',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
        mapping: '{"manual":"手动控制","auto":"自动控制","config":"参数配置","device":"设备"}',
      },
      {
        id: 5,
        f_name: '控制对象',
        db_name: 'field2',
        p_name: 'target',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
        mapping: '{"heat":"加热开关","water":"水泵开关"}',
      },
      {
        id: 6,
        f_name: '控制动作',
        db_name: 'field3',
        p_name: 'action',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
        mapping: '{"on":"开","off":"关"}',
      },
      {
        id: 7,
        f_name: '控制值',
        db_name: 'field4',
        p_name: 'value',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '1',
        mapping: null,
      },
      {
        id: 8,
        f_name: '控制理由',
        db_name: 'field5',
        p_name: 'reason',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
        mapping: null,
      },
    ],
  },

  // ---------- direct_config 默认指令配置（code / ref_code 语义） ----------
  {
    table: 'direct_config',
    keyColumn: 'code',
    rows: [
      {
        code: 'auto',
        ref_code: null,
        ref_value: null,
        t_name: '自动控制',
        f_type: '1',
        f_value: '关:0|开:1',
        mode: null,
        max: null,
        min: null,
        order: '0',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: '0',
      },
      {
        code: 'heat',
        ref_code: 'auto',
        ref_value: '0',
        t_name: '加热开关',
        f_type: '1',
        f_value: '关:0|开:1',
        mode: null,
        max: null,
        min: null,
        order: '1',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: '0',
      },
      {
        code: 'water',
        ref_code: 'auto',
        ref_value: '0',
        t_name: '水泵开关',
        f_type: '1',
        f_value: '关:0|开:1',
        mode: null,
        max: null,
        min: null,
        order: '2',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: '0',
      },
      {
        code: 'pressure_zero',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '压力归零阈值',
        f_type: '3',
        f_value: null,
        mode: null,
        max: '1',
        min: '0',
        order: '10',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'float',
        default_value: '0.01',
      },
      {
        code: 'flow_rate_zero',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '瞬时流量归零阈值',
        f_type: '2',
        f_value: null,
        mode: null,
        max: null,
        min: null,
        order: '11',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'float',
        default_value: '0.01',
      },
      {
        code: 'overpressure_limit',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '过压阈值(kPa)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: null,
        min: null,
        order: '15',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'float',
        default_value: '20',
      },
      {
        code: 'pump_start_grace',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '水泵启动宽限期(s)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: '60',
        min: '0',
        order: '17.5',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'int',
        default_value: '10',
      },
      {
        code: 'flow_unchanged_seconds',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '累计流量不变判定(秒)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: '600',
        min: '1',
        order: '18',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'int',
        default_value: '15',
      },
      {
        code: 'heat_rate_window',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '加热速度计算窗口(s)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: '600',
        min: '10',
        order: '43',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'int',
        default_value: '60',
      },
      {
        code: 'avg_flow_window',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '平均水流计算窗口(s)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: '600',
        min: '10',
        order: '44',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'int',
        default_value: '60',
      },
      {
        code: 'temp1_rise_count',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '温度连续上升次数',
        f_type: '2',
        f_value: null,
        mode: null,
        max: '10',
        min: '2',
        order: '45',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'int',
        default_value: '3',
      },
      {
        code: 'temp2_stable_delta',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '温度稳定波动阈值(°C)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: '10',
        min: '0',
        order: '46',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'float',
        default_value: '0.5',
      },
      // 内部标记（非用户配置）：自动控制判定堵塞时写入 '1'，手动复位后置 '0'
      {
        code: 'blocked',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '堵塞标记',
        f_type: '1',
        f_value: '正常:0|堵塞:1',
        mode: null,
        max: null,
        min: null,
        order: '90',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: '0',
      },
    ],
  },
]
