import { TableSeed } from '@core/database/seeds'

/**
 * 各表默认初始化数据（来源于参考项目 mysql_node_api 的 sql.sql，
 * 并改写为 design_api 的 code / ref_code 语义）。
 * 仅在数据库中存在该表时同步；同步策略为“只补缺失行，不覆盖、不删除”。
 */
export const TABLE_SEEDS: TableSeed[] = [
  // ---------- sensor_data 字段映射（field1..7） ----------
  {
    table: 'sensor_data_mapper',
    keyColumn: 'id',
    rows: [
      {
        id: 1,
        f_name: 'ID',
        db_name: 'id',
        p_name: 'id',
        api_name: null,
        unit: '',
        type: '1',
        visible: '0',
        chartable: '0',
      },
      {
        id: 2,
        f_name: '设备编号',
        db_name: 'd_no',
        p_name: 'id',
        api_name: 'id',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
      },
      {
        id: 3,
        f_name: '数据时间',
        db_name: 'c_time',
        p_name: 'time',
        api_name: 'time',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
      },
      {
        id: 4,
        f_name: '进水温度',
        db_name: 'field1',
        p_name: 'wen_du1',
        api_name: 'temp_in',
        unit: '°C',
        type: '1',
        visible: '1',
        chartable: '1',
      },
      {
        id: 5,
        f_name: '出水温度',
        db_name: 'field2',
        p_name: 'wen_du2',
        api_name: 'temp_out',
        unit: '°C',
        type: '1',
        visible: '1',
        chartable: '1',
      },
      {
        id: 6,
        f_name: '加热开关',
        db_name: 'field3',
        p_name: 'jia_re',
        api_name: 'heat_Y1',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
      },
      {
        id: 7,
        f_name: '水泵状态',
        db_name: 'field4',
        p_name: 'shui_beng',
        api_name: 'water_Y2',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
      },
      {
        id: 8,
        f_name: '流量总计',
        db_name: 'field5',
        p_name: 'liu_liang1',
        api_name: 'liu_liang1',
        unit: 'L',
        type: '1',
        visible: '1',
        chartable: '0',
      },
      {
        id: 9,
        f_name: '瞬时流量',
        db_name: 'field6',
        p_name: 'liu_liang2',
        api_name: 'flow_rate',
        unit: 'L/min',
        type: '1',
        visible: '1',
        chartable: '1',
      },
      {
        id: 10,
        f_name: '水流压力',
        db_name: 'field7',
        p_name: 'pressure',
        api_name: 'pressure',
        unit: 'kPa',
        type: '1',
        visible: '1',
        chartable: '1',
      },
    ],
  },

  // ---------- behavior_data 字段映射（暂无额外字段，仅基础列） ----------
  {
    table: 'behavior_data_mapper',
    keyColumn: 'id',
    rows: [
      {
        id: 1,
        f_name: 'ID',
        db_name: 'id',
        p_name: 'id',
        unit: '',
        type: '1',
        visible: '0',
        chartable: '0',
      },
      {
        id: 2,
        f_name: '设备编号',
        db_name: 'd_no',
        p_name: 'd_no',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
      },
      {
        id: 3,
        f_name: '数据时间',
        db_name: 'c_time',
        p_name: 'c_time',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
      },
    ],
  },

  // ---------- error_msg 字段映射（field1..3） ----------
  {
    table: 'error_msg_mapper',
    keyColumn: 'id',
    rows: [
      {
        id: 1,
        f_name: 'ID',
        db_name: 'id',
        p_name: 'id',
        unit: '',
        type: '1',
        visible: '0',
        chartable: '0',
      },
      {
        id: 2,
        f_name: '设备编号',
        db_name: 'd_no',
        p_name: 'd_no',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
      },
      {
        id: 3,
        f_name: '故障时间',
        db_name: 'c_time',
        p_name: 'c_time',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
      },
      {
        id: 4,
        f_name: '错误信息',
        db_name: 'field1',
        p_name: 'e_msg',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
      },
      {
        id: 5,
        f_name: '错误代码',
        db_name: 'field2',
        p_name: 'e_no',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
      },
      {
        id: 6,
        f_name: '错误类型',
        db_name: 'field3',
        p_name: 'type',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
      },
    ],
  },

  // ---------- control_log 字段映射（field1..5，含值映射词表 mapping） ----------
  {
    table: 'control_log_mapper',
    keyColumn: 'id',
    rows: [
      {
        id: 1,
        f_name: 'ID',
        db_name: 'id',
        p_name: 'id',
        unit: '',
        type: '1',
        visible: '0',
        chartable: '0',
        mapping: null,
      },
      {
        id: 2,
        f_name: '设备编号',
        db_name: 'd_no',
        p_name: 'id',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
        mapping: null,
      },
      {
        id: 3,
        f_name: '操作时间',
        db_name: 'c_time',
        p_name: 'time',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
        mapping: null,
      },
      {
        id: 4,
        f_name: '控制来源',
        db_name: 'field1',
        p_name: 'source',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
        mapping: '{"manual":"手动控制","auto":"自动控制","config":"参数配置","device":"设备"}',
      },
      {
        id: 5,
        f_name: '控制对象',
        db_name: 'field2',
        p_name: 'target',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
        mapping: '{"heat":"加热开关","water":"水泵开关"}',
      },
      {
        id: 6,
        f_name: '控制动作',
        db_name: 'field3',
        p_name: 'action',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
        mapping: '{"on":"开","off":"关"}',
      },
      {
        id: 7,
        f_name: '控制值',
        db_name: 'field4',
        p_name: 'value',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '1',
        mapping: null,
      },
      {
        id: 8,
        f_name: '控制理由',
        db_name: 'field5',
        p_name: 'reason',
        unit: '',
        type: '1',
        visible: '1',
        chartable: '0',
        mapping: null,
      },
    ],
  },

  // ---------- direct_config 默认指令配置（code / ref_code 语义） ----------
  {
    table: 'direct_config',
    keyColumn: 'code',
    rows: [
      {
        code: 'auto',
        ref_code: null,
        ref_value: null,
        t_name: '自动控制',
        f_type: '1',
        f_value: '关:0|开:1',
        mode: null,
        max: null,
        min: null,
        order: '0',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: '0',
      },
      // 隐藏分组根（flow_source 等以 hidden 为 ref_code 的配置的父级，保证外键自引用可满足）
      {
        code: 'hidden',
        ref_code: null,
        ref_value: null,
        t_name: '隐藏（不展示）',
        f_type: '1',
        f_value: null,
        mode: null,
        max: null,
        min: null,
        order: null,
        topic: null,
        preffix: null,
        icon: null,
        type: 'string',
        default_value: null,
      },
      {
        code: 'heat',
        ref_code: 'auto',
        ref_value: '0',
        t_name: '加热开关',
        f_type: '1',
        f_value: '关:0|开:1',
        mode: null,
        max: null,
        min: null,
        order: '1',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: '0',
      },
      {
        code: 'water',
        ref_code: 'auto',
        ref_value: '0',
        t_name: '水泵开关',
        f_type: '1',
        f_value: '关:0|开:1',
        mode: null,
        max: null,
        min: null,
        order: '2',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: '0',
      },
      {
        code: 'dry_burn_protection',
        ref_code: 'auto',
        ref_value: '0',
        t_name: '防干烧保护',
        f_type: '1',
        f_value: '关:0|开:1',
        mode: null,
        max: null,
        min: null,
        order: '3',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: '1',
      },
      {
        code: 'temp_max',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '温度上限',
        f_type: '2',
        f_value: null,
        mode: null,
        max: '100',
        min: '0',
        order: '4',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'float',
        default_value: '35',
      },
      {
        code: 'temp_max_sensor',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '上限检测温度',
        f_type: '5',
        f_value: '进水:1|出水:2',
        mode: null,
        max: null,
        min: null,
        order: '5',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: '2',
      },
      {
        code: 'temp_min',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '温度下限',
        f_type: '2',
        f_value: null,
        mode: null,
        max: '100',
        min: '0',
        order: '6',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'float',
        default_value: '10',
      },
      {
        code: 'temp_min_sensor',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '下限检测温度',
        f_type: '5',
        f_value: '进水:1|出水:2',
        mode: null,
        max: null,
        min: null,
        order: '7',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: '2',
      },
      {
        code: 'temp1_rise_count',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '进水温度连续上升次数',
        f_type: '3',
        f_value: null,
        mode: null,
        max: '10',
        min: '1',
        order: '8',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'int',
        default_value: '3',
      },
      {
        code: 'temp2_stable_delta',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '出水温度稳定阈值',
        f_type: '3',
        f_value: null,
        mode: null,
        max: '10',
        min: '0',
        order: '9',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'float',
        default_value: '0.5',
      },
      {
        code: 'pressure_zero',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '压力归零阈值',
        f_type: '3',
        f_value: null,
        mode: null,
        max: '1',
        min: '0',
        order: '10',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'float',
        default_value: '0.01',
      },
      {
        code: 'flow_rate_zero',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '瞬时流量归零阈值',
        f_type: '2',
        f_value: null,
        mode: null,
        max: null,
        min: null,
        order: '11',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'float',
        default_value: '0.01',
      },
      {
        code: 'flow_target_enabled',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '累计流量目标开关',
        f_type: '1',
        f_value: '关:0|开:1',
        mode: null,
        max: null,
        min: null,
        order: '12',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: '0',
      },
      {
        code: 'flow_source',
        ref_code: 'hidden',
        ref_value: '1',
        t_name: '累计流量来源',
        f_type: '5',
        f_value: '数据验证:0|本地计算:1',
        mode: null,
        max: null,
        min: null,
        order: '13',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: '0',
      },
      {
        code: 'total_flow_target',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '累计流量目标',
        f_type: '2',
        f_value: null,
        mode: null,
        max: null,
        min: null,
        order: '14',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'float',
        default_value: '100',
      },
      {
        code: 'overpressure_limit',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '过压阈值(kPa)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: null,
        min: null,
        order: '15',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'float',
        default_value: '20',
      },
      {
        code: 'overpressure_delay',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '过压恢复检测间隔(s)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: null,
        min: null,
        order: '16',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'int',
        default_value: '5',
      },
      {
        code: 'flow_unchanged_seconds',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '流量不变判定时长(s)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: null,
        min: null,
        order: '17',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'int',
        default_value: '15',
      },
      {
        code: 'reverse_temp_enable',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '逆温差检测开关',
        f_type: '1',
        f_value: '关:0|开:1',
        mode: null,
        max: null,
        min: null,
        order: '18',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: '0',
      },
      {
        code: 'reverse_temp_delta',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '逆温差阈值(°C)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: null,
        min: null,
        order: '19',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'float',
        default_value: '2',
      },
      {
        code: 'reverse_temp_duration',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '逆温差判定时长(s)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: null,
        min: null,
        order: '20',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'int',
        default_value: '180',
      },
      {
        code: 'reverse_temp_pause_control',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '逆温差暂停恒温',
        f_type: '1',
        f_value: '关:0|开:1',
        mode: null,
        max: null,
        min: null,
        order: '21',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: '1',
      },
      {
        code: 'pump_idle_enable',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '空转保护开关',
        f_type: '1',
        f_value: '关:0|开:1',
        mode: null,
        max: null,
        min: null,
        order: '22',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: '0',
      },
      {
        code: 'pump_idle_seconds',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '空转判定时长(s)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: null,
        min: null,
        order: '23',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'int',
        default_value: '3',
      },
      {
        code: 'pump_idle_action',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '空转处置',
        f_type: '5',
        f_value: '仅关泵:off_only|关泵并锁定:off_and_lock',
        mode: null,
        max: null,
        min: null,
        order: '24',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: 'off_only',
      },
      {
        code: 'leak_enable',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '严重泄漏检测开关',
        f_type: '1',
        f_value: '关:0|开:1',
        mode: null,
        max: null,
        min: null,
        order: '25',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: '0',
      },
      {
        code: 'leak_pressure_threshold',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '泄漏压力阈值(kPa)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: null,
        min: null,
        order: '26',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'float',
        default_value: '0.1',
      },
      {
        code: 'leak_flow_threshold',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '泄漏流量阈值(L/min)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: null,
        min: null,
        order: '27',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'float',
        default_value: '0.01',
      },
      {
        code: 'leak_duration',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '泄漏判定时长(s)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: null,
        min: null,
        order: '28',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'int',
        default_value: '3',
      },
      {
        code: 'leak_action',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '泄漏处置',
        f_type: '5',
        f_value: '仅关泵:off_only|关泵并锁定:off_and_lock',
        mode: null,
        max: null,
        min: null,
        order: '29',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: 'off_only',
      },
      {
        code: 'sensor_offline_enable',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '断连检测开关',
        f_type: '1',
        f_value: '关:0|开:1',
        mode: null,
        max: null,
        min: null,
        order: '30',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: '0',
      },
      {
        code: 'sensor_offline_timeout',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '断连判定时长(s)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: null,
        min: null,
        order: '31',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'int',
        default_value: '15',
      },
      {
        code: 'sensor_offline_pause_control',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '断连暂停自动控制',
        f_type: '1',
        f_value: '关:0|开:1',
        mode: null,
        max: null,
        min: null,
        order: '32',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: '1',
      },
      {
        code: 'sensor_spike_enable',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '跳变检测开关',
        f_type: '1',
        f_value: '关:0|开:1',
        mode: null,
        max: null,
        min: null,
        order: '33',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: '0',
      },
      {
        code: 'sensor_spike_ratio',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '跳变阈值(%)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: null,
        min: null,
        order: '34',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'float',
        default_value: '50',
      },
      {
        code: 'sensor_spike_confirm_count',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '跳变确认次数',
        f_type: '2',
        f_value: null,
        mode: null,
        max: null,
        min: null,
        order: '35',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'int',
        default_value: '3',
      },
      {
        code: 'sensor_spike_handle',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '跳变处置',
        f_type: '5',
        f_value: '丢弃不入库:discard|入库标注:mark',
        mode: null,
        max: null,
        min: null,
        order: '36',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: 'discard',
      },
      {
        code: 'sensor_spike_warn',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '跳变轻微警告',
        f_type: '1',
        f_value: '关:0|开:1',
        mode: null,
        max: null,
        min: null,
        order: '37',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: '1',
      },
      {
        code: 'p_f_mismatch_enable',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '压力流量不匹配开关',
        f_type: '1',
        f_value: '关:0|开:1',
        mode: null,
        max: null,
        min: null,
        order: '38',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: '0',
      },
      {
        code: 'p_f_flow_drop_ratio',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '流量下降阈值(%)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: null,
        min: null,
        order: '39',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'float',
        default_value: '30',
      },
      {
        code: 'p_f_pressure_rise_ratio',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '压力上升阈值(%)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: null,
        min: null,
        order: '40',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'float',
        default_value: '20',
      },
      {
        code: 'p_f_window_seconds',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '比较窗口(s)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: null,
        min: null,
        order: '41',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'int',
        default_value: '5',
      },
      {
        code: 'p_f_action',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '压力流量处置',
        f_type: '5',
        f_value: '仅预警:warn_only|关泵:close_pump',
        mode: null,
        max: null,
        min: null,
        order: '42',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: 'warn_only',
      },
      {
        code: 'heat_rate_window',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '加热速度计算窗口(s)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: '600',
        min: '10',
        order: '43',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'int',
        default_value: '60',
      },
      {
        code: 'avg_flow_window',
        ref_code: 'auto',
        ref_value: '1',
        t_name: '平均水流计算窗口(s)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: '600',
        min: '10',
        order: '44',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'int',
        default_value: '60',
      },
      {
        code: 'pid_enable',
        ref_code: 'auto',
        ref_value: '1',
        t_name: 'PID控温开关',
        f_type: '1',
        f_value: '关:0|开:1',
        mode: null,
        max: null,
        min: null,
        order: '45',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: '0',
      },
      {
        code: 'pid_target',
        ref_code: 'pid_enable',
        ref_value: '1',
        t_name: 'PID目标温度(°C)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: '100',
        min: '0',
        order: '46',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'float',
        default_value: '30',
      },
      {
        code: 'pid_sensor',
        ref_code: 'pid_enable',
        ref_value: '1',
        t_name: 'PID检测温度',
        f_type: '5',
        f_value: '进水:1|出水:2',
        mode: null,
        max: null,
        min: null,
        order: '47',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'string',
        default_value: '2',
      },
      {
        code: 'pid_kp',
        ref_code: 'pid_enable',
        ref_value: '1',
        t_name: 'PID比例系数Kp',
        f_type: '2',
        f_value: null,
        mode: null,
        max: null,
        min: null,
        order: '48',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'float',
        default_value: '20',
      },
      {
        code: 'pid_ki',
        ref_code: 'pid_enable',
        ref_value: '1',
        t_name: 'PID积分系数Ki',
        f_type: '2',
        f_value: null,
        mode: null,
        max: null,
        min: null,
        order: '49',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'float',
        default_value: '1',
      },
      {
        code: 'pid_kd',
        ref_code: 'pid_enable',
        ref_value: '1',
        t_name: 'PID微分系数Kd',
        f_type: '2',
        f_value: null,
        mode: null,
        max: null,
        min: null,
        order: '50',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'float',
        default_value: '5',
      },
      {
        code: 'pid_precision',
        ref_code: 'pid_enable',
        ref_value: '1',
        t_name: 'PID精确度(°C)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: '5',
        min: '0',
        order: '51',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'float',
        default_value: '0.1',
      },
      {
        code: 'pid_offset_limit',
        ref_code: 'pid_enable',
        ref_value: '1',
        t_name: 'PID最大偏移(°C)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: '5',
        min: '0',
        order: '52',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'float',
        default_value: '0.2',
      },
      {
        code: 'pid_cycle',
        ref_code: 'pid_enable',
        ref_value: '1',
        t_name: 'PID控制周期(s)',
        f_type: '2',
        f_value: null,
        mode: null,
        max: '600',
        min: '1',
        order: '53',
        topic: 'control',
        preffix: null,
        icon: null,
        type: 'int',
        default_value: '10',
      },
    ],
  },
]
